# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Design pattern NINJA
email: contact@designpattern.ninja
description: "Community-driven, open catalog of software design patterns."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://designpattern.ninja" # the base hostname & protocol for your site
github_username:  mfidemraizer

# Build settings
markdown: kramdown

# Contribution settings
contributors:
    anonymous:
        fullName: "Anonymous"
        siteUrl: "http://designpattern.ninja"
        avatarUrl: "/img/anonymous_author_avatar.png"
    mfidemraizer:
        fullName: "Matías Fidemraizer"
        siteUrl: "http://matiasfidemraizer.com"
        avatarUrl: "https://www.gravatar.com/avatar/41e7ea21270a6079bb14d6d60ec75d8a"
    eevans:
        fullName: "Eric Evans"
        siteUrl: "https://www.linkedin.com/in/ericevansddd"
        avatarUrl: "https://media.licdn.com/media/p/4/000/162/04b/1d33a7a.jpg"


# Tagging
mainTags: 
    - architectural
    - creational
    - behavioral
    - object-mapping